### ISSUE TITLE
The armor isn't showing

### ISSUE THREAD

**Issue by joeyak** [DorkixAzIgazi/armored-elytra#3]
**Describe the bug**
Only the elytra is showing.

**Expected behavior**
The armor is showing with the elytra.

**Screenshots**
This is a screenshot of the bug
![image](https://github.com/user-attachments/assets/f057f731-074a-4418-930e-5671b6d9748d)

Here is a screenshot from someone else also with the mod
![image](https://github.com/user-attachments/assets/7854524b-eb3d-45d0-99db-012afe5ea57e)

Computer Specs
CPU: AMD Ryzen 5 5500 3.6 GHz
RAM: 16 GB DDR4 3600 MHz
GPU: AMD Radeon RX 6700 10GB
STORAGE: 1 TB PCI-E Gen4 NVMe SSD
OS: Windows 11 Home 64 Bit

Here is the minecraft log https://mclo.gs/qpKvG6D

**Comment by DorkixAzIgazi** [comment]
@joeyak Hello! Make sure you install the mod into your minecraft client aswell! From the logs it seems like you don't have it installed. All model rendering is done on the client side.

**Comment by joeyak** [comment]
For some reason the modrinth client didn't install it on the player's computer when she installed the modpack. Now that she's manually added it, it's working. Thank you!

**Comment by marduk7780** [comment]
where do you find the client side part? i can't seem to find it.

**Comment by DorkixAzIgazi** [comment]
> where do you find the client side part? i can't seem to find it.

Both the client and server code is in the same file. You just have to add it to your Minecraft client's mods folder. Fabric will run the only the client code if you connect to servers, and both the client and server code in singleplayer.

**Comment by marduk7780** [comment]
i dont get it, i have it installed in the normal mods folder in .minecraft but it doesnt show in single player
![mdlctn](https://github.com/user-attachments/assets/2ea8771a-01ed-44f2-bf4d-4e6197696921)
![Screenshot 2024-08-01 155100](https://github.com/user-attachments/assets/a965fd53-8fa0-40e0-9540-7f4859547571)
i am using the advanced netherite stuff too but i doubt that'd affect it

**Comment by DorkixAzIgazi** [comment]
> i dont get it, i have it installed in the normal mods folder in .minecraft but it doesnt show in single player
> ![mdlctn](https://github.com/user-attachments/assets/2ea8771a-01ed-44f2-bf4d-4e6197696921)
> ![Screenshot 2024-08-01 155100](https://github.com/user-attachments/assets/a965fd53-8fa0-40e0-9540-7f4859547571)
> i am using the advanced netherite stuff too but i doubt that'd affect it 
> 

Short answer: currently no support for other mods.
Long answer with why I don't: https://github.com/DorkixAzIgazi/armored-elytra/issues/2#issuecomment-2232871211

**Comment by marduk7780** [comment]
ah ok fair enough, thank you!
